// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ3olvX0vR5XSB7W8eFtMd4HdhoXmp0uw',
    appId: '1:241792538078:web:649c6383a2d8f69fcf394f',
    messagingSenderId: '241792538078',
    projectId: 'auth-app-a3188',
    authDomain: 'auth-app-a3188.firebaseapp.com',
    storageBucket: 'auth-app-a3188.firebasestorage.app',
    measurementId: 'G-9TPXS4VNXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8RUuH3iZPPGqljTWQ0_FEtc1PI1WBpTA',
    appId: '1:241792538078:android:75235816aaba4f29cf394f',
    messagingSenderId: '241792538078',
    projectId: 'auth-app-a3188',
    storageBucket: 'auth-app-a3188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDYp9udNfBfPZHNFLi_QVGhOkCxidlQmw',
    appId: '1:241792538078:ios:075d6a5b251651a1cf394f',
    messagingSenderId: '241792538078',
    projectId: 'auth-app-a3188',
    storageBucket: 'auth-app-a3188.firebasestorage.app',
    androidClientId: '241792538078-m2cocm1i9pcstons24vof5bcfgr11uor.apps.googleusercontent.com',
    iosClientId: '241792538078-41r3u1a99vnf6ffc2u7vkqvrvhn08389.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDYp9udNfBfPZHNFLi_QVGhOkCxidlQmw',
    appId: '1:241792538078:ios:075d6a5b251651a1cf394f',
    messagingSenderId: '241792538078',
    projectId: 'auth-app-a3188',
    storageBucket: 'auth-app-a3188.firebasestorage.app',
    androidClientId: '241792538078-m2cocm1i9pcstons24vof5bcfgr11uor.apps.googleusercontent.com',
    iosClientId: '241792538078-41r3u1a99vnf6ffc2u7vkqvrvhn08389.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ3olvX0vR5XSB7W8eFtMd4HdhoXmp0uw',
    appId: '1:241792538078:web:345c132fa0d25be9cf394f',
    messagingSenderId: '241792538078',
    projectId: 'auth-app-a3188',
    authDomain: 'auth-app-a3188.firebaseapp.com',
    storageBucket: 'auth-app-a3188.firebasestorage.app',
    measurementId: 'G-8ZR32BR2LQ',
  );
}
